# Generated by Django 5.2.7 on 2025-10-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recipients',
            field=models.ManyToManyField(blank=True, through='campaigns.EmailDeliveryLog', to='campaigns.recipient'),
        ),
        migrations.AlterUniqueTogether(
            name='emaildeliverylog',
            unique_together={('campaign', 'recipient')},
        ),
    ]
